site_name: Popper
theme:
  bootstrap4
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false

markdown_extensions: 
  - fenced_code
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/languages/ocaml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/languages/lisp.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - css/extra.css